version: "3"
services:
  strapi:
    container_name: strapi
    build: .
    image: strapi:latest
    restart: unless-stopped
    environment:
      NODE_ENV: development
      HOST: 0.0.0.0
      PORT: 1337
      APP_KEYS: INXynmK8eMOIZPc4+FvsaQ==,fe7eqzpdg+SN4eiIkO+ZwA==,2ofau2+wQ82D+lAtcMt8JQ==,jswg3FGfs0OnK83XqyqyRA==
      API_TOKEN_SALT: l04vzSIZhPtPcIDg/1ARwg==
      ADMIN_JWT_SECRET: zZRAvzQosxZKFnxYT4YzIA==
      TRANSFER_TOKEN_SALT: ymV8UG8NKfe/yCVvkc8fRQ==
      DATABASE_CLIENT: mysql
      DATABASE_HOST: strapiDB
      DATABASE_PORT: 3306
      DATABASE_NAME: strapi_poc
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: root
      JWT_SECRET: vnvHUBMbsFA8NnQ2OJyalQ==
    volumes:
      - ./config:/opt/app/config
      - ./src:/opt/app/src
      - ./package.json:/opt/package.json
      - ./yarn.lock:/opt/yarn.lock
      - ./.env:/opt/app/.env
      - ./public/uploads:/opt/app/public/uploads
    ports:
      - "1337:1337"
    networks:
      - strapi
    depends_on:
      - strapiDB

  strapiDB:
    container_name: strapiDB
    platform: linux/amd64 #for platform error on Apple M1 chips
    restart: unless-stopped
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: strapi_poc
    volumes:
      - strapi-data:/var/lib/mysql
      #- ./data:/var/lib/mysql # if you want to use a bind folder
    ports:
      - "3307:3306"
    networks:
      - strapi

volumes:
  strapi-data:

networks:
  strapi:
    name: Strapi
    driver: bridge