version: '3'

services:
  strapi:
    build: .
    ports:
      - '1337:1337'
    depends_on:
      - mysql
    environment:
      HOST: 0.0.0.0
      PORT: 1337
      APP_KEYS: INXynmK8eMOIZPc4+FvsaQ==,fe7eqzpdg+SN4eiIkO+ZwA==,2ofau2+wQ82D+lAtcMt8JQ==,jswg3FGfs0OnK83XqyqyRA==
      API_TOKEN_SALT: l04vzSIZhPtPcIDg/1ARwg==
      ADMIN_JWT_SECRET: zZRAvzQosxZKFnxYT4YzIA==
      TRANSFER_TOKEN_SALT: ymV8UG8NKfe/yCVvkc8fRQ==
      DATABASE_CLIENT: mysql
      DATABASE_HOST: mysql
      DATABASE_PORT: 3306
      DATABASE_NAME: strapi_poc
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: root
      DATABASE_SSL: false
      JWT_SECRET: vnvHUBMbsFA8NnQ2OJyalQ==
    volumes:
      - .:/usr/src/app
    networks:
      - strapi-network

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: strapi_poc
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - strapi-network
    ports:
      - '3307:3306'

volumes:
  mysql_data:

networks:
  strapi-network:
